name: Docker Server to Update BIND Named with Docker Hostnames

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: alpine-latest
    steps:
    - uses: actions/checkout@v3
      name: Build the Docker image
#      run: docker build . --file Dockerfile --rm=true --tag nagiosxi:$(date +%s)

#    - name: Dockerize
#      if: success()
#      uses: manusa/actions-publish-docker@v1.1.2
#      with:
#        name: nbetcher/nagiosxi
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: '--allow-insecure-entitlement security.insecure'

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: nbetcher/docker-hostdns
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
       builder: ${{ steps.buildx.outputs.name }}
       context: .
       push: true
       file: Dockerfile
       allow: security.insecure
       platforms: linux/amd64
       tags: nbetcher/docker-hostdns:latest
       labels: ${{ steps.meta.outputs.labels }}
